"""Add ModerationResult model

Revision ID: 7d69a36a89d4
Revises: 0a41a2e7900a
Create Date: 2025-02-12 18:08:42.323599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7d69a36a89d4'
down_revision: Union[str, None] = '0a41a2e7900a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('moderation_results', sa.Column('text', sa.String(), nullable=False))
    op.add_column('moderation_results', sa.Column('flagged', sa.Boolean(), nullable=False))
    op.add_column('moderation_results', sa.Column('categories', sa.JSON(), nullable=False))
    op.drop_column('moderation_results', 'content')
    op.drop_column('moderation_results', 'is_flagged')
    op.drop_column('moderation_results', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('moderation_results', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('moderation_results', sa.Column('is_flagged', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('moderation_results', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('moderation_results', 'categories')
    op.drop_column('moderation_results', 'flagged')
    op.drop_column('moderation_results', 'text')
    # ### end Alembic commands ###
