"""Add ModerationResult model

Revision ID: a81d36b48cfd
Revises: 7d69a36a89d4
Create Date: 2025-02-12 18:47:06.394131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a81d36b48cfd'
down_revision: Union[str, None] = '7d69a36a89d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
