"""after several errors

Revision ID: ad3d5b7229e6
Revises: a81d36b48cfd
Create Date: 2025-02-14 21:04:35.815635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ad3d5b7229e6'
down_revision: Union[str, None] = 'a81d36b48cfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_moderation_results_id', table_name='moderation_results')
    op.drop_table('moderation_results')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moderation_results',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('flagged', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('categories', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='moderation_results_pkey')
    )
    op.create_index('ix_moderation_results_id', 'moderation_results', ['id'], unique=False)
    # ### end Alembic commands ###
